### PR TITLE
Add missing <limits> for GCC 11

### PR DESCRIPTION
**Pull request by pb-dseifert**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by ahehn-nv** [comment]
ok to test

**Comment by EpiSlim** [comment]
ok to test

**Comment by EpiSlim** [comment]
Hey @ohadmo, can you please launch the CI on gpuCI? Is there a way I can initialise the CI myself?

**Comment by ohadmo** [comment]
ok to test

**Review by ahehn-nv — APPROVED** [review]

**Pull request merged**
